<a href="https://colab.research.google.com/github/chlduddn0920/2025.dm/blob/main/4%EC%A3%BC%EC%B0%A8_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
A= {1,2,3}
B={2,3,4}
R={(1,2),(2,3),(3,2),(3,4)}
print("관계 A :",R)

관계 A : {(2, 3), (3, 2), (1, 2), (3, 4)}


In [11]:
import numpy as np

A_list = sorted(A)
B_list = sorted(B)

relation_matrix = np.zeros((len(A_list), len(B_list)), dtype=int)

for i, a in enumerate(A_list):
  for j, b in enumerate(B_list):
    if (a, b) in R:
      relation_matrix[i, j] = 1

print("관계 행렬:")
print(relation_matrix)

관계 행렬:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [17]:
# R: A -> B
# S: B -> C
C = {'x','y'}
S = {(2,'x'),(3,'y'),(4,'x')}

# 합성 관게 R °S
composed_relation = set()

for (a,b1) in R:
  for (b2,c) in S:
    if b1 == b2:
      composed_relation.add((a,c))

print("\n합성 관계 R °S :", composed_relation)

합성 관계 R °S : {(3, 'x'), (1, 'x'), (2, 'y')}
